### PR TITLE
Attempt to resolve version number not being detected by FDroid

### PR DESCRIPTION
**Pull request by m00head**
@Rudloff @Izzysoft One or more of the 3 changed files below may fix the following issue:
https://github.com/friimaind/pi-hole-droid/issues/20#issuecomment-545146551

### CODE REVIEW

**Comment by m00head** [comment]
@Rudloff Will this file also need to be updated with the correct version number?
https://gitlab.com/Rudloff/fdroiddata/blob/develop/metadata/friimaind.piholedroid.yml

**Comment by IzzySoft** [comment]
Yes, that should help. Especially making it literal in the gradle.

**Comment by Rudloff** [comment]
I you tag your versions correctly, `friimaind.piholedroid.yml` should be updated automatically.

**Comment by m00head** [comment]
As the v1.0.5 tag already exists (before my changes), will this mean we will either have to force re-tag v.1.0.5 or have to use a new tag v.1.0.6?

https://github.com/friimaind/pi-hole-droid/releases

**Comment by m00head** [comment]
@friimaind Please will you review this change, and merge it if you happy with it?

**Comment by m00head** [comment]
@friimaind Please will you review this change, and merge it if you happy with it?

**Comment by m00head** [comment]
I have created a merge request on the FDroid GitLab site to use the latest version tag:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6786

**Comment by m00head** [comment]
@friimaind Please will you tag the latest commit on master (https://github.com/friimaind/pi-hole-droid/commit/fd06eda5b96de9dec078c15ad90143df8f770223) as `v1.0.5` (not `1.0.5` with missing `v` prefix) to so that FDroid will detect the correct version number:
https://github.com/friimaind/pi-hole-droid/tags

**Comment by friimaind** [comment]
@m00head done!

**Pull request merged**
